config/routes.rb
Rails.application.routes.draw do
  root "species#index"
  resources :species do
    resources :sightings
  end
  resources :sightings

  resources :regions

end

app/models/day.rb
class Day < ActiveRecord::Base
  has_many :sightings
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :sightings
  validates :name, presence: true
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :species
  belongs_to :region
  validates :lat, presence: true
  validates :long, presence: true
  validates :date, presence: true

end

app/models/species.rb
class Species < ActiveRecord::Base
  validates :name, presence: true
  has_many :sightings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def show
    @day = Day.find(params[:id])
    render :show
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  def index
    @regions = Region.all
  end

  def new
    @region = Region.new
    render :new
  end

  def create
    @region = Region.new(region_params)
    if @region.save
      redirect_to regions_path
    else
      flash[:danger] = @region.errors.full_messages.first
      render :new
    end
  end

  def show
    @region = Region.find(params[:id])
    render :show
  end


private

  def region_params
    params.require(:region).permit(:name)
  end

end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :find_sighting, except: [:create, :new, :index]
  before_action :find_species, except: [:index]

  def index
    @species = Species.all
    if params.keys.length == 2
      @sightings = Sighting.all
    else
      if params[:date] != "" && params[:species] != ""
        @sightings = Sighting.where({date: params[:date], species_id: params[:species]})
      elsif params[:species] != ""
        @sightings = Sighting.where({species_id: params[:species]})
      elsif params[:date] != ""
        @sightings = Sighting.where({date: params[:date]})
      else
        @sightings = Sighting.all
      end
    end
    render :index
  end

  def show
    render :show
  end

  def new
    @sighting = Sighting.new
    render :new
  end

  def create
    @sighting = @species.sightings.new(sighting_params)
    if @sighting.save
      redirect_to species_path(@species)
    else
      flash[:danger] = @sighting.errors.full_messages.first
      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    if @sighting.update(sighting_params)
      redirect_to species_path(@sighting.species)
    else
      flash[:danger] = @sighting.errors.full_messages.first
      render :edit
    end
  end

  def destroy
    @sighting.destroy
    redirect_to species_path(@species)
  end

private
  def sighting_params
    params.require(:sighting).permit(:lat, :long, :date, :region_id)
  end
  def find_sighting
    @sighting = Sighting.find(params[:id])
  end
  def find_species
    @species = Species.find(params[:species_id])
  end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  before_action :find_species, except: [:create, :index, :new]
  def index
    @species = Species.all
    render :index
  end

  def new
    @species = Species.new
    render 'new'
  end

  def create
    @species = Species.new(species_params)
    if @species.save
      redirect_to species_index_path
    else
      flash[:danger] = @species.errors.full_messages.first
      render :new
    end
  end

  def show
    render :show
  end

  def edit
    render :edit
  end

  def update
    if @species.update(species_params)
      redirect_to species_path(@species)
    else
      flash[:danger] = @species.errors.full_messages.first
      render :edit
    end
  end

  def destroy
    @species.destroy
    redirect_to species_index_path
  end

private

  def find_species
    @species = Species.find(params[:id])
  end

  def species_params
    params.require(:species).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Looks like there was an error or two:</h3>
  <ul>
    <% object.errors.full_messages.each do |m| %>
      <li><%= m %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WildlifeTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Wild Animals</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="/regions">Regions</a></li>
        <li><a href="/sightings">Sightings</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/regions/_form.html.erb
<%= form_for @region do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/regions/index.html.erb
<%= link_to "Add Region", new_region_path %>
<ul>
  <% @regions.each do |region| %>
    <li>
      <%= link_to region.name, region_path(region) %>
    </li>
  <% end %>
</ul>

app/views/regions/new.html.erb
<%= render "form" %>

app/views/regions/show.html.erb
<h1><%= @region.name %></h1>
<ul>

  <% @region.sightings.each do |sighting| %>

    <li><strong>Species:</strong> <%= sighting.species.name %> <strong>Date sighted:</strong> <%= link_to sighting.date, species_sighting_path(sighting.species, sighting) %></li>

  <% end %>

</ul>
<%= link_to "Back", regions_path %>

app/views/sightings/_form.html.erb
<%= form_for [@species, @sighting] do |f| %>
  <%= f.label :lat %>
  <%= f.number_field :lat, class: 'text_field', step: 0.0000001 %>
  <%= f.label :long %>
  <%= f.number_field :long, class: 'text_field', step: 0.0000001 %>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <%= f.collection_select :region_id, Region.order(:name),:id,:name %>
  <%= f.submit %>
<% end %>

app/views/sightings/edit.html.erb
<%= render "form" %>

app/views/sightings/index.html.erb
<h1>Sightings</h1>

<%= form_tag({:action => :index}, {:method => :get}) do %>
  <%= date_field_tag "date" %>
  <%= select_tag "species", options_from_collection_for_select(@species, "id", "name"), include_blank: true %>
  <%= submit_tag "Filter" %>
<% end %>



<ul>
  <% @sightings.each do |sighting| %>
    <li><%= sighting.species.name %></li>
  <% end %>
</ul>

app/views/sightings/new.html.erb
<%= render 'form' %>

app/views/sightings/show.html.erb
<h1><%= @sighting.date %></h1>

app/views/species/_form.html.erb
<%= form_for @species do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/species/index.html.erb
<h1>Species Central</h1>
<%= link_to 'Add Species', new_species_path %>
<ul>
  <% @species.each do |s| %>
    <li><%= link_to s.name, species_path(s) %></li >
  <% end %>
</ul>

app/views/species/new.html.erb
<%= render 'form' %>

app/views/species/show.html.erb
<h1><%= @species.name %></h1>
<%= link_to "Add Sighting", new_species_sighting_path(@species) %>
<%= link_to "Edit", edit_species_path(@species) %>
<%= link_to "Delete", species_path(@species), data: { confirm: "Are you sure?",
                                                     method: "delete" } %>
<ul>
<% @species.sightings.each do |sighting| %>
  <li>
    <strong>Date: </strong><%= sighting.date %> <strong>・</strong>
    <strong>Region: </strong><%= link_to sighting.region.name, region_path(sighting.region) %> <strong>・</strong>
    <strong>Lat: </strong><%= sighting.lat %> <strong>・</strong>
    <strong>Long: </strong><%= sighting.long %> |
    <%= link_to "Edit", edit_species_sighting_path(@species, sighting) %> |
    <%= link_to "Delete", species_sighting_path(@species, sighting), data: { confirm: "You sure, dude?",
                                                                             method: "delete" } %>
  </li>
<% end %>
</ul>